repository: boxin6/boxin6.github.io
repository_url: https://github.com/boxin6/boxin6.github.io

timezone: Asia/Shanghai
lang: zh_CN

title: text导航 · Qiesheng
alias_en: Qiesheng-find
alias_cn: text导航
description: A Navigation Website for test
keywords: text导航, Box, Yub, XUPT, Navi, Navigation
url: https://boxin6.github.io/
established_at: "2016-10-01T00:00+08:00"

author: Box
author_url: boxin6@yeah.net
organization: TEELAB
organization_url: https://teelab.net
contact: contact[at]irockbunny[dot]com

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo.png
logo_white: /images/logo.png

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor
